In [24]:
import numpy as np

a= np.array([1,2,3,4,5],dtype='int32')
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
 

[[9. 8. 7.]
 [6. 5. 4.]]


In [25]:
#Get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [26]:
b.shape
#Get type
a.dtype
#Get size
a.itemsize

4

In [27]:
#Get total size
a.nbytes

20

In [29]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
#Get a specific elemet[r,c]
a[1,5]

np.int64(13)

In [32]:
#Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
#Get Specific Column
a[:,2]

array([ 3, 10])

In [34]:
#Getting[startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [35]:
 a[1,5]

np.int64(13)

In [36]:
a[1,5]=20

In [37]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [38]:
a[:,2]=5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [43]:
# 3D array exmaple
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
#Get Specific element
b[0,1,1]

np.int64(4)

In [45]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [47]:
#replace
b[:,1,:]=[[9,9],[8,8]]

In [48]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [51]:
#All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
#All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [56]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [58]:
#Any other number(full_like)
np.full_like(b,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [60]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.64679205, 0.37455954],
       [0.65899653, 0.68759304],
       [0.05568404, 0.51137456],
       [0.13347257, 0.23794378]])

In [61]:
np.random.random_sample(a.shape)

array([[0.58652388, 0.15170534, 0.48052024, 0.04430914, 0.64320383,
        0.13685715, 0.3574601 ],
       [0.13646251, 0.70932912, 0.18848766, 0.0592891 , 0.42205463,
        0.05694859, 0.5446638 ]])

In [65]:
#Random Integer values
np.random.randint(1,7,size=(3,3))

array([[2, 5, 2],
       [1, 4, 6],
       [3, 5, 1]])

In [ ]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
arr = np.array([[1,2,3]])
r1 =np.repeat(arr,3,axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
output = np.ones((5,5))
z= np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##Be careful when copying arrays

In [75]:
#Example
a=np.array([1,2,3])
b=a
b[0]=100
print(a)
#Changes the value of a

[100   2   3]


In [77]:
#Write approach to copy the array
a =np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


Mathematics

In [78]:
a =np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [79]:
a+2

array([3, 4, 5, 6])

In [80]:
a-2

array([-1,  0,  1,  2])

In [81]:
a*2

array([2, 4, 6, 8])

In [82]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [83]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [84]:
a**2

array([ 1,  4,  9, 16])

In [85]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [86]:
np.cos(b)

array([0.54030231, 1.        , 0.54030231, 1.        ])

Linear Algebra

In [89]:
a=np.ones((2,3))
print(a)
b= np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [92]:
c=np.identity(3)
np.linalg.det(c)


np.float64(1.0)

Statstics

In [94]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
np.min(stats,axis=1)

array([1, 4])

In [99]:
np.max(stats)

np.int64(6)

In [100]:
np.sum(stats,axis=0)

array([5, 7, 9])

Reorganizing Arrays

In [105]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [106]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([4,5,6,7])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

In [108]:
#Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Miscellaneous

In [ ]:
#Load from file
np.genfromtxt('data.txt',delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [112]:
filedata =np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

Boolean masking and advanced indexing

In [113]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [114]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [115]:
#You can index with a list in NumPY
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [116]:
v1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
v1


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [119]:
v1[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [122]:
v1[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [126]:
v1[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])